# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

# Add application configuration variables here, as shown below.
#
ADMIN_NAME: First User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: changeme
GA_CLIENT_ID: 637941761856.apps.googleusercontent.com
GA_SECRET: Qn7uh6AG0Y3en-NNqM0X-ot_
FULL_CONTACT_API_KEY: d39f9b411b368b6d
MANDRILL_USER_NAME: team@badge.co
MANDRILL_API_KEY: 4ifikFe1NO-pkxJJ9hG4zA
TWILIO_ACCOUNT_SID: ACca40ad9b385aa26d07d2a927c5b2d071
TWILIO_AUTH_TOKEN: 36c8bb21a80efba1fd809094b35c6bad
TWILIO_FROM_NUMBER: +1 207-618-8946
FIREBASE_URL: https://badge-dev.firebaseio.com/
GROCER_CERT: badge-adhoc.pem
GROCER_PASS: snowboard12
GROCER_ENDPOINT: gateway.push.apple.com
BUGSNAG_API_KEY: f7039da9a0bcf75663356b181a7e42dd
INTERCOM_APP_ID: 5f50e0c798d99997d289d68d41287fc59de15c64
INTERCOM_API_KEY: 7a9eb75d23ecaa228669f51a2698052899ce6cc8
AWS_ACCESS_KEY_ID: AKIAIMFJRPGLNT7FTLFQ
AWS_SECRET_ACCESS_KEY: 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
AWS_REGION: 'us-west-2'

staging:
  GA_CLIENT_ID: 466421541427-hm6pjklidk8pgossbc8t78480rq9kbd8.apps.googleusercontent.com
  GA_SECRET: HNUaNxxPbi8RU3Mbhhagr-nv
  INTERNAL_API_TOKEN: 20566ad05aaa5828ad6c3a6c73329db5108e4baba29814c59dbe5569e7c12be8
  GCM_KEY: AIzaSyC5iPpyCeQY1sfvoplNHikzL-sndqJvooY

production:
  GA_CLIENT_ID: 466421541427-a0imgmrrg2gm24sfodk3tt6l9sk5p97s.apps.googleusercontent.com
  GA_SECRET: dGiCSgf6kD2nBC7klB0MDMrW
  INTERNAL_API_TOKEN: f9c93bc9ca8a0fe561c2ca3eb132cdbed7a70bd4095ed9212063edd3a4825255
  FIREBASE_URL: https://badge-prod.firebaseio.com/
  GCM_KEY: f7039da9a0bcf75663356b181a7e42dd

