# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

# Add application configuration variables here, as shown below.
#
ADMIN_NAME: First User
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: changeme
GA_CLIENT_ID: 637941761856.apps.googleusercontent.com
GA_SECRET: Qn7uh6AG0Y3en-NNqM0X-ot_
FULL_CONTACT_API_KEY: d39f9b411b368b6d
MANDRILL_USER_NAME: team@badge.co
MANDRILL_API_KEY: 4ifikFe1NO-pkxJJ9hG4zA
TWILIO_ACCOUNT_SID: ACca40ad9b385aa26d07d2a927c5b2d071
TWILIO_AUTH_TOKEN: 36c8bb21a80efba1fd809094b35c6bad
TWILIO_FROM_NUMBER: +1 207-618-8946
FIREBASE_URL: https://badge-dev.firebaseio.com/
GROCER_CERT: headshot-dev-apns.pem
GROCER_PASS: snowboard12
GROCER_ENDPOINT: gateway.sandbox.push.apple.com


production:
  GA_CLIENT_ID: 735228360361-qt7vofvrlat880q27g096sfqhaee39ih.apps.googleusercontent.com
  GA_SECRET: KTX0cuMOM1hkk1KxXKyVg3Mn
  FIREBASE_URL: https://badge-prod.firebaseio.com/
  GROCER_CERT: badge-adhoc.pem
  GROCER_PASS: snowboard12
  GROCER_ENDPOINT: gateway.push.push.apple.com
